### PR TITLE
fix: Add error message in the event of error on repo tree query

### LINKED ISSUE #85: Intermittent 502 Gateway Timeout Errors When Processing Repositories
## Summary
We're experiencing intermittent 502 Bad Gateway errors when trying to process certain GitHub repositories — most recently observed with the `perlweeklychallenge-club` repo. This issue is not deterministic: the same repository might succeed on one attempt but fail on another, even with retries.

## Details
**Issue**
The plugin `perlweeklychallenge-club` is failing during payload fetch:

```
non-200 OK status code: 502 Bad Gateway
````

**Error Payload:**

```
{
  "data": null,
  "errors": [
    {
      "message": "Something went wrong while executing your query on 2025-05-09T08:44:58+00:00.
      This may be the result of a timeout, or it could be a GitHub bug.
      Please include `74EA:12EF:1E4F625:1F7700D:681DC07F` when reporting this issue."
    }
  ]
}
````

**Observed Behavior:**
- The issue is intermittent and non-deterministic.
- Reprocessing the same repository sometimes works, sometimes fails.
- In some cases, even after 5 retries, we still fail to retrieve the data.
- This results in slower processing, additional compute overhead, and inconsistent test results.

### LINKED ISSUE #88: Recursively loading all subdirectories is uneccessarily slow
❓ We're recursively loading all subdirectories and their contents. For very large repositories, this could be slow or resource-intensive. If we expect very large repos, should we consider lazy loading subdirectories or allowing a max recursion depth as a parameter?

_Originally posted by @jmeridth in https://github.com/revanite-io/pvtr-github-repo/pull/87#discussion_r2118411588_

### PR DESCRIPTION
**Pull request by eddie-knight**
This resolves #85 by adding an `Unknown` status for repos that we cannot query the contents of (502 due to repo size).

This resolves #88 by _not_ changing to recursively get every directory, because this proved to be just as problematic by instantly hitting the rate limit threshold when scanning a large repo.

### CODE REVIEW

File: evaluation_plans/osps/quality/steps.go [hunk 1]
```diff
@@ -124,18 +124,24 @@ func statusChecksAreRequiredByBranchProtection(payloadData interface{}, _ map[st
...
 	}
 
-	if len(data.SuspectedBinaries) == 0 {
-		return layer4.Passed, "No binaries were found in the repository (Note: this check only examines file names at this time)"
+	// TODO: This only checks the top 3 levels of the repository tree
+	// for common binary file extensions and it fails on very large repositories.
+	suspectedBinaries, err := data.GetSuspectedBinaries()
+	if err != nil {
+		data.Config.Logger.Trace(fmt.Sprintf("unexpected response while checking for binaries: %s", err.Error()))
+		return layer4.Unknown, "Error while scanning repository for binaries, potentially due to repo size. See logs for details."
```
Comment (jmeridth) [inline evaluation_plans/osps/quality/steps.go:138]: I'm a fan of the fail fast method. I'm asking other clarifying questions privately but this is good for me.

**Review by jmeridth — APPROVED** [review]
