### PR TITLE
fix: Removed retrieval of full dependency manifest data

### LINKED ISSUE #77: Failed to load payload for github-repo: timedout
**Description**

Running the plugin against big monorepos with many dependency files results in timeout from one of the GraphQl queries . The the [dependencyGraphManifests](https://github.com/revanite-io/pvtr-github-repo/blob/eff5bcb63b70227b76ca41a54d834164eafebea9/data/graphql-data.go#L92) part in [GraphqlRepoData](https://github.com/revanite-io/pvtr-github-repo/blob/eff5bcb63b70227b76ca41a54d834164eafebea9/data/graphql-data.go#L13-L14) causes the whole query to time out

**Configuration**
```
loglevel: trace
write-directory: evaluation_results
write: true
output: json
services:
  crowd.dev:
    plugin: github-repo

    policy:
      catalogs:
        - OSPS_B
      applicability:
        - Maturity Level 1

    vars:
      owner: CrowdDotDev
      repo: crowd.dev
      token: <redacted>
```

**Output**
```
./privateer run
2025/04/29 15:24:50 vars: map[]
2025-04-29T15:24:56.493+0200 [ERROR] tests failed in plugin crowd.dev: Failed to load payload for github-repo: timedout
```

**Expected Behavior**
The plugin should be creating crowd.dev.json under `evaluation_results/crowd.dev`

**Actual Behavior**
Log file [crowd.dev.log](https://github.com/user-attachments/files/19959985/crowd.dev.log) is created, but json (`crowd.dev.json`) is missing

### PR DESCRIPTION
**Pull request by eddie-knight**
This change splits up the graphql calls into different files for clarity, and cuts down the dependency manifest call significantly.

The change to the test is debatable... I spent a bunch of time refining the second half of a check that I think won't even be reached. I left a note on that in the function `countDependencyManifests`.

Regardless, this resolves #77

### CODE REVIEW

File: data/graphql-data.go [hunk 1]
```diff
@@ -1,11 +1,6 @@
 package data
 
 import (
-	"context"
-	"fmt"
-	"path/filepath"
-
-	"github.com/privateerproj/privateer-sdk/config"
 	"github.com/shurcooL/githubv4"
```
Comment (trumant) [inline data/graphql-data.go:4]:
```suggestion
```

File: evaluation_plans/osps/quality/steps.go [hunk 2]
```diff
@@ -246,26 +242,31 @@ func isManifestFile(filename string, pattern string) bool {
...
 		return layer4.Unknown, message
 	}
 
+	manifestsCount := data.DependencyManifestsCount
+	if manifestsCount > 0 {
+		return layer4.Passed, fmt.Sprintf("Found %d dependency manifests from GitHub API", manifestsCount)
+	}
+
+	// Note: I'm not sure whether the rest of this logic will ever be needed as GitHub is detecting the manifests automatically
+	// Also, the repository tree is limited to three levels deep currently, so this isn't guaranteed to find all manifests
```
Comment (trumant) [inline evaluation_plans/osps/quality/steps.go:257]: If in the future we provide the ability to run checks against a git repository on the local filesystem (common use case for github actions workflows and for maintainer/contributor validation of changes as they work to comply) I can imagine it would be helpful to support our own repository search for manifests.

But, if GitHub's API can reliably report the manifests as-is, I'd argue we should actively avoid alternative implementations (like this one below) until such time as we support filesystem evaluation

**Review by trumant — DISMISSED** [review]
I like the direction of this refactor.

I'd be fine merging as-is and I'm also supportive of removing the tree walk and relying solely on the GraphQL query for the count.

**Comment by eddie-knight** [comment]
<details><summary>Removed file search logic</summary>

```go

/////////////////////////////////////////////
// Future check for dependency manifest files
// This function checks for the presence of known dependency management files in the repository
// and verifies whether they contain dependencies.

func future_checkDependencyManifestFiles(payloadData interface{}, _ map[string]*layer4.Change) (result layer4.Result, message string) {
	data, message := reusable_steps.VerifyPayload(payloadData)
	if message != "" {
		return layer4.Unknown, message
	}

	if data.Repository.Object.Tree.Entries == nil {
		return layer4.Unknown, "Repository tree entries not available"
	}

	entries := data.Repository.Object.Tree.Entries

	foundManifests := make(map[string]ManifestResult)

	// Check repository contents for dependency files
	for _, entry := range entries {
		for _, manifest := range knownManifests {
			if isManifestFile(filepath.Base(entry.Name), manifest.Filename) {
				result := ManifestResult{
					Found:    true,
					Language: manifest.Language,
					Manifest: entry.Name,
				}
				foundManifests[manifest.Language] = result
			}
		}
	}

	if len(foundManifests) == 0 {
		return layer4.Failed, "No dependency management files found"
	}

	for lang, result := range foundManifests {
		result.HasDeps = true
		foundManifests[lang] = result
		break
	}

	missingDeps := []string{}
	withDeps := []string{}
	for lang, result := range foundManifests {
		if !result.HasDeps {
			missingDeps = append(missingDeps,
				fmt.Sprintf("%s (%s)", result.Manifest, lang))
		} else {
			withDeps = append(withDeps,
				fmt.Sprintf("%s (%s)", result.Manifest, lang))
		}
	}

	result = layer4.NeedsReview
	if len(withDeps) > 0 {
		message = fmt.Sprintf("Good dependency management files found: %s ", strings.Join(withDeps, ", "))
		result = layer4.Passed
	}
	if len(missingDeps) > 0 {
		missingDepsMessage := fmt.Sprintf("Missing dependencies in %s", strings.Join(missingDeps, ", "))
		message = strings.Join([]string{message, missingDepsMessage}, " | ")
		result = layer4.Failed
	}
	return result, message
}

type DependencyManifest struct {
	Filename string
	Language string
}

// Known dependency management files for various languages
var knownManifests = []DependencyManifest{
	{"go.mod", "Go"},
	{"package.json", "JavaScript/Node.js"},
	{"pom.xml", "Java (Maven)"},
	{"build.gradle", "Java (Gradle)"},
	{"requirements.txt", "Python"},
	{"Pipfile", "Python (Pipenv)"},
	{"pyproject.toml", "Python (Poetry)"},
	{"Gemfile", "Ruby"},
	{"composer.json", "PHP"},
	{"Cargo.toml", "Rust"},
	{"*.csproj", ".NET"},
	{"mix.exs", "Elixir"},
}

// ManifestResult stores the validation result for a manifest
type ManifestResult struct {
	Found    bool
	Language string
	HasDeps  bool
	Manifest string
}

func isManifestFile(filename string, pattern string) bool {
	if strings.Contains(pattern, "*") {
		matched, _ := filepath.Match(pattern, filename)
		return matched
	}
	return filename == pattern
}
```

**Review by trumant — APPROVED** [review]
Love it!
